AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an EC2 instance which enables SSH connection. 

Resources:
  MehmetCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: the_doctor
      SecurityGroups:
        - launch-wizard-8
      Tags:
        - Key: Name
          Value: mehmet-cf-instance
      UserData: 
        Fn::Base64: !Sub |
           #!/bin/bash -xe
           yum update -y
           yum install -y httpd.x86_64
           systemctl start httpd.service
           systemctl enable httpd.service
           usermod -a -G apache ec2-user
           chown -R ec2-user:apache /var/www
           chmod -R 777 /var/www/html
           cd /var/www/html/
           wget https://raw.githubusercontent.com/mehmetafsar510/aws_devops/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
           systemctl restart httpd