apiVersion: v1
kind: Service   
metadata:
  name: web_server_service
  labels:
    app: phonebook
spec:
  type: NodePort  
  ports:
  - port: 3000  
    nodePort: 30001
    targetPort: 5000
  selector:
    app: phonebook