apiVersion: apps/v1
kind: Deployment
metadata:
  name: web_server
  labels:
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
      - name: web_server
        image: web_server
        ports:
        - containerPort: 80